#!/bin/sh
export NDK_HOME=/Users/daixiang/Android/AndroidIDE/ndk-r13
export PATH=$NDK_HOME:$PATH

cd blacksiren/libjsonc
ndk-build clean
ndk-build -j8

cd ../libbsiren
ndk-build clean
ndk-build -j8

cd ..
ndk-build clean
ndk-build -j8
